<div style="margin-top: 5px;color:#CC0000;">System Setting</div>
<div style="margin-top: 20px;"><b>Email Templates Setting</b></div>
<div style="margin-top:8px;background-color:#FFF;border:1px solid green;">
<form id="configform" method="post" action=""><table border=0 cellspacing=1 cellpadding=4 width=100% style="font-size:9px;" bgcolor=green>
		<tr bgcolor="#ffffff"><td align="center">
	<textarea name="mailconfig" style="width:98%;height:300px;margin:0px auto"><?=$this->escape($this->mailconfig)?></textarea>
	</td></tr><tr bgcolor="#ffffff"><td><input type="submit" value="Save" />&nbsp;&nbsp;<input type="reset" value="Reset" />
	</td>
	</tr>
</table></form>
</div>