<!doctype html public "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/tr/html4/loose.dtd">
<html>
<head>
<?php 
	$request = Zend_Controller_Front::getInstance()->getRequest(); 
	$base_url = $request->getBaseUrl();
	$base_url .= '/public';
	$this->headTitle('Miccostumes.com') 
           ->headTitle($request->getControllerName()) 
           ->setSeparator(' | '); 

	$this->headLink()->appendStylesheet($base_url."/css/stylesheet.css"); 
	$this->headScript()->prependFile($base_url.'/js/jquery-1.3.2.js');
?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<?php echo $this->headTitle();?>
<meta name="keywords" content="" />
<meta name="description" content="" />
<?php echo $this->headScript();?>
<base>
<?php
	echo $this->headLink(); 
?>
</head>
<body>
<div class="content cfix">
	<!-- header begin-->
	<div class="header">
		<?php echo $this->layout()->header; ?>
	</div>
	<!-- header end-->
	<div class="mainbody mt0">
	<!-- left begin-->
	<div class="left">
		<?php echo $this->layout()->content; ?>
	</div>
	<!-- left end-->

	<!-- right begin-->
	<div class="right">
		<?php echo $this->layout()->right; ?>
	</div>
	<!-- right end-->
	</div>
</div>
<!-- footer begin-->
<div class="footer"><?php echo $this->layout()->footer; ?></div>
<!-- footer end-->
</body>
</html>