<div style="color:#CC0000;font-size:12px;">Please input search condition!</div>
<div>
	<?php echo $this->search_form;?>
</div>
<?php
$request = Zend_Controller_Front::getInstance()->getRequest(); 
$base_url = $request->getBaseUrl();
$base_url .= '/public';
$this->headScript()->appendFile($base_url.'/js/datepicker/jquery.datepick.js');
$this->headLink()->appendStylesheet($base_url.'/js/datepicker/redmond.datepick.css');
?>
<script type="text/javascript">
(function($){
	$('#beginDate').datepick({closeAtTop:false,dateFormat:'yy-mm-dd',defaultDate:$('#start_date').val(),showBigPrevNext:true});
	$('#endDate').datepick({closeAtTop:false,dateFormat:'yy-mm-dd',showBigPrevNext:true});
})(jQuery);
</script>