<div style="color:#CC0000;font-size:12px;">Control Panel Login</div>
<div>
	<form id="login_form" name="login_form" action="<?php echo $this->url(
            array('controller'=>'login','action'=>'login'), 'default', true); ?>" method="POST">
		<div>User ID:</div>
		<div><?php echo $this->formText('login_id', '', array('size' => 18)); ?></div>
		<div>&nbsp;</div>
		<div>Login Password:</div>
		<div><?php echo $this->formPassword('login_pass', '', array('size' => 18)); ?></div>
		<div>&nbsp;</div>
		<?php echo $this->formHidden('action','login');?>
		<div><?php echo $this->formSubmit('submit','Submit'); ?></div>
	</form>
</div>