<div><a href="<?php echo $this->url(array('controller'=>'Merchantlist'), 'default', true);?>">Merchant List</a></div>
<div><a href="<?php echo $this->url(array('controller'=>'Withdrawtrans'), 'default', true);?>">Withdraw Application</a></div>
<div><a href="#">Month Payment</a></div>
<div><a href="<?php echo $this->url(array('controller'=>'Chargeback'), 'default', true);?>">ChargeBack Block</a></div>
<div><a href="#">User List</a></div>
<div><a href="#">Report</a></div>